steps:
- name: gcr.io/cloud-builders/docker
  dir: spinnaker-monitoring-daemon
  args: ["build", "-t", "gcr.io/$PROJECT_ID/monitoring-daemon:$TAG_NAME", "-f", "Dockerfile", "."]
  env: ["GRADLE_USER_HOME=/gradle_cache/.gradle"]
images:
- gcr.io/$PROJECT_ID/monitoring-daemon:$TAG_NAME
timeout: 3600s
options:
  machineType: N1_HIGHCPU_8
