steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: spinnaker-monitoring-daemon
  args: ["build",
         "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA",
         "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME",
         "-f", "Dockerfile",
         "."]
images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME'
